### ISSUE TITLE
Go install fails parsing go mod

### ISSUE THREAD

**Issue by adilw3nomad** [oltarzewskik/tibivi#6]
Env: `go version go1.19 darwin/amd64`

Running `go get -u github.com/strang1ato/tibivi` as said in the readme mentions returns this error

```
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
 ```

However running `go install github.com/strang1ato/tibivi@latest` returns this error

```
go install github.com/strang1ato/tibivi@latest                                                                                                at  04:57:16 ─╯
go: github.com/strang1ato/tibivi@latest: github.com/strang1ato/tibivi@v1.0.2: parsing go.mod:
        module declares its path as: github.com/oltarzewskik/tibivi
                but was required as: github.com/strang1ato/tibivi
```

I think this may have been caused by this [commit](https://github.com/adilw3nomad/tibivi/commit/6e29ae1a5238d432678d45669bdcd02127ccbc71)

**Comment by adilw3nomad** [comment]
disregard, I used [goenv](https://github.com/syndbg/goenv) to install go 1.14 and then ran `go get -u github.com/strang1ato/tibivi` and it's all working as intended.

**Comment by strang1ato** [comment]
@adilw3nomad Thank you for showing your interest for this repo! You are right, this project should be upgraded to newer version of go. If you are willing to do that, feel free to submit a PR which will upgrade towards new version of go
